### ISSUE TITLE
Create a landing page for Capnet Assist [$25]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#814]
Right now it's just pointing to our home page which looks like an ad. We should make a simple "error" page it can point to that explains why this window has appeared/what capnet is/we messed up somewhere

Ideally, users should never see this, but for some reason they are.

--

[Bounty on Bountysource](https://www.bountysource.com/issues/26103693-create-a-landing-page-for-capnet-assist)

**Comment by cassidyjames** [comment]
Is this too verbose? I almost feel like we should just do the first part. If we have to explain the second part, we're doing something wrong and should fix it. :P

> ## You're connected!
> Your Internet connection appears to be working. You can safely close this window and continue using your device.
> #### Why is this window appearing?
> elementary OS automatically checks your Internet connection when you connect to a new WiFi network. If it detects there is not an Internet connection (i.e. if you are connecting to a captive portal at a coffee shop or other public location), this window will appear and display the login page.

> Some networks can appear to be a captive portal at first, triggering this window, then actually end up connecting. In those cases, you'll see this message and can safely close the window.

**Comment by cassidyjames** [comment]
I do think it's important to note that this page shouldn't necessarily "look" like a normal page on the website. It should probably look more like a native message without any header or footer since it's only intended to be displayed in the OS inside the capnet window.

**Comment by danrabbit** [comment]
I agree it should look native and not like a part of our website.

I mean the thing is we know we're doing something wrong and should fix it, but it's still happening anyways. I think we should still fail elegantly. That copy looks fine to me :)

**Comment by lewisgoddard** [comment]
Do we want tracking on this page? One one hand, I love having the statistic, on the other, tracking in the OS the user hasn't necessarily asked for.

**Comment by cassidyjames** [comment]
I think we would have to disable Google Analytics for sure (since nobody is opting into that). But I'm not against a simple hit counter that just tracks how many times people hit the page. Because that's very valuable to us in making sure that fewer people hit it. :) Also, if it's _just_ a hit counter and not collecting or storing any IPs or other info, I think it's perfectly acceptable.

**Comment by danrabbit** [comment]
I'm very concerned about having any kind of areas for criticism. I'd prefer not to do any kind of tracking here. Especially because we very explicitly declare on the front page that there's no tracking in the OS

**Comment by lewisgoddard** [comment]
Exactly what I was thinking, I'd be _very_ hesitant about putting any kind of tracking on such a page.

**Comment by lewisgoddard** [comment]
Since [/generate_204](https://elementary.io/generate_204) now exists, I think this bug is kind of defunct.

**Comment by danrabbit** [comment]
We still need a placeholder page that capnet will attempt to load before it gets redirected to the portal login. This is separate from the initial 204 page that it attempts to ping

**Comment by lewisgoddard** [comment]
Can we not just try and load /generate_204? Mine always closes automatically, so I assumed that was what it was doing.

**Comment by danrabbit** [comment]
Well I think we should consider that the only time this will show is when Capnet fucked up. So now instead of loading our home page, it will load a blank page :p I'm not sure that's a vast improvement

**Comment by lewisgoddard** [comment]
How about a simple HTML page with minimal styling, mostly just fonts, and the text cassidy suggested?

**Comment by danrabbit** [comment]
+1. It doesn't have to be fancy :)
